apiVersion: apps/v1
kind: Deployment
metadata:
  name: alex-app-deployment
  labels:
    app: alex-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: alexcontainerapp
        image: alexhomeacr.azurecr.io/alexcontainerapp:v1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi