name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        path: main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build the alexcontainerapp Docker image
      run: |
        docker build ./main/src/AlexContainerApp/ --tag ghcr.io/aleksandrshvets/alexcontainerapp:${GITHUB_SHA::8}
        docker push ghcr.io/aleksandrshvets/alexcontainerapp:${GITHUB_SHA::8}
    
    - name: Checkout environment repo
      uses: actions/checkout@v2
      with:
        repository: aleksandrshvets/environment-repo
        path: environment
        
    - name: Create file
      run: |
        echo "apiVersion: apps/v1" > environment/kustomize/deployment.yaml
        echo "kind: Deployment" >> environment/kustomize/deployment.yaml
        echo "metadata:" >> environment/kustomize/deployment.yaml
        echo "  name: alex-app-deployment" >> environment/kustomize/deployment.yaml
        echo "  labels:" >> environment/kustomize/deployment.yaml
        echo "    app: alex-app" >> environment/kustomize/deployment.yaml
        echo "spec:" >> environment/kustomize/deployment.yaml
        echo "  selector:" >> environment/kustomize/deployment.yaml
        echo "    matchLabels:" >> environment/kustomize/deployment.yaml
        echo "      app: alex-app" >> environment/kustomize/deployment.yaml
        echo "  template:" >> environment/kustomize/deployment.yaml
        echo "    metadata:" >> environment/kustomize/deployment.yaml
        echo "      labels:" >> environment/kustomize/deployment.yaml
        echo "        app: alex-app" >> environment/kustomize/deployment.yaml
        echo "    spec:" >> environment/kustomize/deployment.yaml
        echo "      imagePullSecrets:" >> environment/kustomize/deployment.yaml
        echo "      - name: regcred-github" >> environment/kustomize/deployment.yaml
        echo "      containers:" >> environment/kustomize/deployment.yaml
        echo "      - name: alexcontainerapp" >> environment/kustomize/deployment.yaml
        echo "        image: ghcr.io/aleksandrshvets/alexcontainerapp:${GITHUB_SHA::8}" >> environment/kustomize/deployment.yaml
        echo "        imagePullPolicy: Always" >> environment/kustomize/deployment.yaml
        echo "        ports:" >> environment/kustomize/deployment.yaml
        echo "        - name: http" >> environment/kustomize/deployment.yaml
        echo "          containerPort: 8080" >> environment/kustomize/deployment.yaml
        echo "          protocol: TCP" >> environment/kustomize/deployment.yaml
        echo "        resources:" >> environment/kustomize/deployment.yaml
        echo "          limits:" >> environment/kustomize/deployment.yaml
        echo "            cpu: 2000m" >> environment/kustomize/deployment.yaml
        echo "            memory: 512Mi" >> environment/kustomize/deployment.yaml
        echo "          requests:" >> environment/kustomize/deployment.yaml
        echo "            cpu: 100m" >> environment/kustomize/deployment.yaml
        echo "            memory: 64Mi" >> environment/kustomize/deployment.yaml
    - name: Commit files
      working-directory: ./environment
      run: |
        git config --local user.email "aliaksandr.shvets@gmail.com"
        git config --local user.name "aliaksandrshvets"
        git add kustomize/deployment.yaml
        git commit -m "[skip ci] Change image tag to ${GITHUB_SHA::8}" -a
        git push --force --quiet "https://aleksandrshvets:${{ secrets.PUSH_PULL_PAT }}@github.com/aleksandrshvets/environment-repo"