name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker build ./src/AlexContainerApp/ --tag ghcr.io/aleksandrshvets/alexcontainerapp:latest
        docker push ghcr.io/aleksandrshvets/alexcontainerapp:latest